services:
  crud-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_CONNECTION_STRING: host=postgres user=postgres password=postgres dbname=postgres sslmode=disable

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
