GET http://localhost:8080/api/items

###

POST http://localhost:8080/api/items
Content-Type: application/json

{
    "name": "Item #1",
    "price": 10,
    "quantity": 5
}

###

GET http://localhost:8080/api/items/4